version: '3.9'

services:
  node:
    depends_on:
      - app
    image: node:21-alpine3.18
    restart: unless-stopped
    volumes:
      - ./app/wp-content/themes/dusha-wp-theme:/var/www/html
    working_dir: /var/www/html
#    entrypoint: ["npm"]

  app:
    depends_on:
      - db
    image: wordpress:6.4.3-apache
    restart: unless-stopped
    ports:
      - '8080:80'
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: '${MARIADB_DATABASE}'
      WORDPRESS_DB_USER: '${MARIADB_USER}'
      WORDPRESS_DB_PASSWORD: '${MARIADB_PASSWORD}'
    volumes:
      - ./app:/var/www/html
    networks:
      - wp-network

  db:
    image: mariadb:10.6.4-focal
    mem_limit: 2048m
    restart: unless-stopped
    ports:
      - '3306:3306'
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MARIADB_USER: '${MARIADB_USER}'
      MARIADB_DATABASE: '${MARIADB_DATABASE}'
      MARIADB_PASSWORD: '${MARIADB_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wp-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    env_file: .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wp-network
volumes:
  db-data:
networks:
  wp-network:
    driver: bridge